### PR TITLE
Add makefile for easier installation

### PR DESCRIPTION
**Pull request by cjheinze**
Added a makefile to make installation a little bit easier. Great project! :)

### CODE REVIEW

**Comment by stelabouras** [comment]
Hey @cjheinze, thanks for the PR!

A `Makefile` is indeed a great addition! That said, I was thinking of locking down the dependencies to specific versions / branches, to avoid cases where an updated package would break the build process. I have a commit ready and will push it as soon as possible.

Also, given that the `/usr/local/bin/` directory is not writable without `sudo`, maybe we should update the `README` instructions to mention `sudo make install` instead of `make install`.

What do you think?

**Comment by cjheinze** [comment]
Hey! 
Sounds like a good idea to lock down the versions. I'll remove the package update from the Makefile.
And yes that also seems reasonable! I forgot that it is protected nowadays :)

**Comment by stelabouras** [comment]
Done! I have pushed version 0.0.16 that locks down the versions of the dependencies!

**Comment by stelabouras** [comment]
Do you need to rebase your branch before I squash and merge those 2 commits?

**Comment by cjheinze** [comment]
No conflicts so just go ahead and squash :)

**Comment by stelabouras** [comment]
Done, thank you for your contribution!

**Pull request merged**
